name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install gtest
      uses: MarkusJx/googletest-installer@v1.1
    
    - name: Install GCC 
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install gcc-snapshot
        sudo apt-get install gcc-6 g++-6

    - name: Build 
      run: |
        cmake -S . -B build
        cmake --build build

    - name: Test
      run: |
        cd build && ctest
        cd ..
      
