name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install gtest
      uses: MarkusJx/googletest-installer@v1.1
    
    - name: Install GCC
      # You may pin to the exact commit or the version.
      # uses: egor-tensin/setup-gcc@d04208cef6e985db0830428975fc2ab3f28d89a1
      uses: egor-tensin/setup-gcc@v1
      with:
        # GCC version to install
        version: # optional, default is latest
        # Target platform
        platform: # optional, default is x64
        # Install Cygwin packages
        cygwin: # optional, default is 0
        # Set up cc/gcc/c++/g++ executables
        cc: # optional, default is 1
        # On Cygwin, replace executable symlinks with hardlinks
        hardlinks: # optional, default is 0

    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: run unit test
      run: |
        cmake -S . -B build
        cmake --build build
        cd build && ctest
        cd ..
      
